### PR TITLE
Issue/93/revert to radius tracer

### PR DESCRIPTION
**Pull request by combet**
This is addressing issue #93. We do need a radius tracer rather than a tag to compute the covariance between radial bin of the cluster shear profile. 
- radius traver added
- demo notebook updated to use radius tracer and not tags.

### CODE REVIEW

**Review by eduardojsbarroso — APPROVED** [review]
It seems that everything is good to me. @joezuntz can you merge? ( if you think this change is ok.)

**Comment by vitenti** [comment]
Hello everyone, maybe it's a good idea to also copy back the tests. @eduardojsbarroso @combet

**Comment by combet** [comment]
Oh yeah, thanks for reminding us @vitenti.

**Comment by combet** [comment]
RadiusTracer tests are back in - thanks @vitenti.

**Review by eduardojsbarroso — APPROVED** [review]

**Pull request merged**
